#BELOW IS AN EXAMPLE OF SINGLE LINE COMMENT  {{ ctrl+/ }}

# print("hi i am a good boy
#       and he is bad boy")

print("hi i am a good boy \n even he is a good boy\nyes he is!!!")


# BELOW IS AN EXAMPLE OF MULTIPLE LINE COMMENT


# single quotes :-
'''
I AM CURRENTLY USING MULTILINE COMMENT.
WHERE I CAN WRITE ANY COMMENT INSIDE TRIPLE SINGLE QUOTES OR EVEN I CAN USE TRIPLE DOUBLE QUOTE
AND WILL SIMPLY ACT AS COMMENT
'''

#double quotes:-
"""
I AM CURRENTLY USING MULTILINE COMMENT.
WHERE I CAN WRITE ANY COMMENT INSIDE TRIPLE SINGLE QUOTES OR EVEN I CAN USE TRIPLE DOUBLE QUOTE
AND WILL SIMPLY ACT AS COMMENT
"""
